MODEL:
  NAME: 'ResNet-152'
  BACKBONE:
    NAME: 'ResNet-152'
    INPUT_RESOLUTION: 64
    OUT_CHENNELS: 2048
  RESNET:
    BLOCK_NUM: [0, 3, 8, 36, 3]
    POOLER_SCALE: [0.5, 0.25, 0.125, 0.0625, 0.03125]
  CLASSIFIER:
    NUM_CLASSES: 10

DATASETS:
  TRAIN: ('data', )
  VAL: ('data', )
  TRAIN_BATCH_SIZE: 64

SOLVER:
  CUDA: False
  LEARNING_RATE: 0.1
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5.0e-4
  MAX_ITER: 200
  STRATEGY: 'MBGD'
  CHECKPOINT: 100
  OUTPUT_DIR: 'checkpoint/'

